version: "3"

networks:
  sonarnet:

services:
  sonarqube:
    container_name: sonarqube_10_6
    image: sonarqube:10.6-community
    restart: unless-stopped
    depends_on:
      - postgresql
    expose:
      - 9000
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonar_sonarqube_data:/opt/sonarqube/data
      - sonar_sonarqube_extensions:/opt/sonarqube/extensions
      - sonar_sonarqube_logs:/opt/sonarqube/logs

  postgresql:
    container_name: postgresql_10_6
    image: postgres:12.19
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonar_postgresql_data:/var/lib/postgresql/data

volumes:
  sonar_sonarqube_data:
    name: sonar_10_6_sonarqube_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\sonarqube\10_6\sonar_sonarqube_data
  sonar_sonarqube_extensions:
    name: sonar_10_6_sonarqube_extensions
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\sonarqube\10_6\sonar_sonarqube_extensions
  sonar_sonarqube_logs:
    name: sonar_10_6_sonarqube_logs
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\sonarqube\10_6\sonar_onarqube_logs
  sonar_postgresql_data:
    name: sonar_10_6_postgresql_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\sonarqube\10_6\sonar_postgresql_data
